### ISSUE TITLE
Character image double

### ISSUE THREAD

**Issue by TugaPowerROM** [PainedPsyche/cui_character#50] opened 2021-08-24 20:21 UTC
cui_character branche : dev

Using latest ESX Legacy with multichar enabled, when creating character it will show double as the image, it also have skinchanger menu opened after creating character in cui, any workround for this ?

![imagem](https://user-images.githubusercontent.com/9769460/130684285-118ca2e3-ec01-4839-9f07-df23141c9ce4.png)

**Comment by PainedPsyche** [comment] 2021-08-30 09:11
Should be fixed with [this comit](https://github.com/PainedPsyche/cui_character/commit/0ae7a3e891793f13e9de8f609bff6439cce4f569).

> also have skinchanger menu opened after creating character in cui, any workround for this ?

Not a workaround, but a requirement: you need to **disable skinchanger and esx_skin entirely**.

**Closed by PainedPsyche** 2021-08-30 09:11 UTC

**Comment by mschiegg** [comment] 2021-12-02 15:16
Hey @PainedPsyche 
The Problem is not fixed with this release.
I've the same Problems as the Issue Opener.
Double Image (Only on new Charakter) and Skin Menü after Spawning (Only on new Charakter)

Can you have a look at this?

Many Thanks
